//! Password generation for enrolled cameras.
//!
//! The device tells us its rules up front via systemready's
//! `passphrasepolicy`, so the generated password is built to satisfy the
//! reported policy rather than guessed at.

use rand::seq::SliceRandom;
use rand::Rng;

use crate::vapix::systemready::PassphrasePolicy;

/// Characters that are safe to carry through a URL, a YAML double-quoted
/// scalar, and a shell argument without escaping surprises. Deliberately
/// excludes quotes, backslash, backtick, dollar, and the shell metacharacters.
const LOWER: &[u8] = b"abcdefghijkmnopqrstuvwxyz"; // no 'l'
const UPPER: &[u8] = b"ABCDEFGHJKLMNPQRSTUVWXYZ"; // no 'I', 'O'
const DIGIT: &[u8] = b"23456789"; // no '0', '1'
const SPECIAL: &[u8] = b"-_.+=:@%#";

/// Minimum length we generate, regardless of policy.
///
/// 20 clears the strictest documented policy (`length`, 15) with margin, and
/// costs nothing since nobody types these by hand.
const DEFAULT_LENGTH: usize = 20;

/// The shortest password each policy accepts.
pub fn policy_minimum(policy: PassphrasePolicy) -> usize {
    match policy {
        PassphrasePolicy::None => 8,
        PassphrasePolicy::Complex => 12,
        PassphrasePolicy::Length => 15,
        // Field absent (older AXIS OS) — assume the strictest.
        PassphrasePolicy::Unknown => 15,
    }
}

/// Generate a password satisfying `policy`.
///
/// `requested` overrides the length; it is raised to the policy minimum if it
/// would fall short. The result always contains at least one lowercase,
/// uppercase, digit and special character, which satisfies `complex` and, by
/// being long enough, every other policy at the same time.
pub fn generate(policy: PassphrasePolicy, requested: Option<usize>) -> String {
    let min = policy_minimum(policy);
    let len = requested.unwrap_or(DEFAULT_LENGTH).max(min).min(64);

    let mut rng = rand::thread_rng();
    let mut chars: Vec<u8> = Vec::with_capacity(len);

    // One of each class first, so complexity holds no matter the draw.
    chars.push(*LOWER.choose(&mut rng).unwrap());
    chars.push(*UPPER.choose(&mut rng).unwrap());
    chars.push(*DIGIT.choose(&mut rng).unwrap());
    chars.push(*SPECIAL.choose(&mut rng).unwrap());

    let all: Vec<u8> = [LOWER, UPPER, DIGIT, SPECIAL].concat();
    while chars.len() < len {
        chars.push(all[rng.gen_range(0..all.len())]);
    }

    chars.shuffle(&mut rng);
    String::from_utf8(chars).expect("generated bytes are ASCII")
}

/// Check a password against a policy. Used to verify our own output, and to
/// validate a user-supplied `--pwd` before it is sent to the camera.
pub fn satisfies(pw: &str, policy: PassphrasePolicy) -> Result<(), String> {
    let min = policy_minimum(policy);
    if pw.chars().count() < min {
        return Err(format!(
            "password is {} characters, policy '{}' requires at least {}",
            pw.chars().count(),
            policy.as_str(),
            min
        ));
    }
    if pw.len() > 64 {
        return Err("password exceeds the VAPIX maximum of 64 characters".into());
    }
    // VAPIX strict_pwd: printable ASCII only.
    if let Some(bad) = pw.chars().find(|c| (*c as u32) < 0x20 || (*c as u32) > 0x7E) {
        return Err(format!(
            "password contains a character outside ASCII 0x20-0x7E: {:?}",
            bad
        ));
    }
    if policy == PassphrasePolicy::Complex || policy == PassphrasePolicy::Unknown {
        let has = |f: fn(&char) -> bool| pw.chars().any(|c| f(&c));
        if !has(|c| c.is_ascii_lowercase()) {
            return Err("policy 'complex' requires a lowercase letter".into());
        }
        if !has(|c| c.is_ascii_uppercase()) {
            return Err("policy 'complex' requires an uppercase letter".into());
        }
        if !has(|c| c.is_ascii_digit()) {
            return Err("policy 'complex' requires a digit".into());
        }
        if !has(|c| c.is_ascii_punctuation() || *c == ' ') {
            return Err("policy 'complex' requires a special character".into());
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const POLICIES: [PassphrasePolicy; 4] = [
        PassphrasePolicy::None,
        PassphrasePolicy::Length,
        PassphrasePolicy::Complex,
        PassphrasePolicy::Unknown,
    ];

    #[test]
    fn generated_passwords_satisfy_their_own_policy() {
        for policy in POLICIES {
            for _ in 0..200 {
                let pw = generate(policy, None);
                satisfies(&pw, policy)
                    .unwrap_or_else(|e| panic!("policy {:?} produced {:?}: {}", policy, pw, e));
            }
        }
    }

    #[test]
    fn generated_passwords_satisfy_every_policy() {
        // The default output should be good enough for any device we meet,
        // including ones that report no policy but enforce one anyway.
        for _ in 0..200 {
            let pw = generate(PassphrasePolicy::None, None);
            for policy in POLICIES {
                satisfies(&pw, policy).unwrap();
            }
        }
    }

    #[test]
    fn short_request_is_raised_to_policy_minimum() {
        let pw = generate(PassphrasePolicy::Length, Some(4));
        assert!(pw.chars().count() >= 15);
        let pw = generate(PassphrasePolicy::Complex, Some(4));
        assert!(pw.chars().count() >= 12);
    }

    #[test]
    fn length_is_capped_at_vapix_maximum() {
        let pw = generate(PassphrasePolicy::None, Some(500));
        assert_eq!(pw.chars().count(), 64);
        satisfies(&pw, PassphrasePolicy::Complex).unwrap();
    }

    #[test]
    fn only_url_yaml_and_shell_safe_characters() {
        for _ in 0..200 {
            let pw = generate(PassphrasePolicy::Complex, None);
            for c in pw.chars() {
                assert!(
                    !"\"'\\`$!&|;<>()[]{}*?~^ ".contains(c),
                    "unsafe character {:?} in {:?}",
                    c,
                    pw
                );
                assert!(c.is_ascii_graphic(), "non-printable {:?}", c);
            }
        }
    }

    #[test]
    fn no_visually_ambiguous_characters() {
        for _ in 0..100 {
            let pw = generate(PassphrasePolicy::Complex, None);
            for c in "l1IO0".chars() {
                assert!(!pw.contains(c), "ambiguous {:?} in {:?}", c, pw);
            }
        }
    }

    #[test]
    fn passwords_are_not_repeated() {
        let a: Vec<String> = (0..50).map(|_| generate(PassphrasePolicy::None, None)).collect();
        let mut uniq = a.clone();
        uniq.sort();
        uniq.dedup();
        assert_eq!(uniq.len(), a.len(), "generator repeated a password");
    }

    #[test]
    fn rejects_too_short() {
        assert!(satisfies("Ab3-", PassphrasePolicy::Length).is_err());
        assert!(satisfies(&"Ab3-".repeat(3), PassphrasePolicy::Length).is_err());
    }

    #[test]
    fn rejects_missing_complexity_class() {
        // 20 lowercase letters: long enough for `length`, wrong for `complex`.
        let pw = "abcdefghijkmnopqrstu";
        satisfies(pw, PassphrasePolicy::Length).unwrap();
        assert!(satisfies(pw, PassphrasePolicy::Complex).is_err());
    }

    #[test]
    fn rejects_non_ascii_and_overlong() {
        assert!(satisfies("Abcdefghijklmn3-ö", PassphrasePolicy::Length).is_err());
        assert!(satisfies(&"a".repeat(65), PassphrasePolicy::None).is_err());
    }
}
